### ISSUE TITLE
Incorrect exception used in deposit catch block

### ISSUE THREAD

**Issue by ewhanson** [pkp/crossref-ops#16]
The exception type-hinted in the catch block does not correspond to the exception thrown, so the catch block is bypassed. This ignores the DOI-related actions in the catch block and causes the job to be registered as a failure.

https://github.com/pkp/crossref-ops/blob/c7bd46caefae65a4161f0dd1eed587e076eae330/CrossRefExportPlugin.php#L366

It should use `GuzzleHttp\Exception\GuzzleException` instead.

**Comment by ewhanson** [comment]
@bozana, would you mind reviewing this? It's a small change but it was causing DOI depositing jobs to fail. Thanks!

PR:

- #17

**Comment by bozana** [comment]
I think this issue can be closed...
